# Golang environment for build

FROM golang:1.9.4-alpine
RUN echo 'https://mirror.tuna.tsinghua.edu.cn/alpine/edge/community' > /etc/apk/repositories
RUN echo 'https://mirror.tuna.tsinghua.edu.cn/alpine/v3.6/main' >> /etc/apk/repositories
RUN apk add --no-cache bash git gcc musl-dev libc-dev upx
