import { DialogModule, TableOfContentsModule } from '@alauda/ui';
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { ApplicationApiService, ContainerLogApiService } from '@app/api';
import { FeatureSharedCommonModule } from '@app/features-shared/common';
import { PipelineModule } from '@app/modules/pipeline/pipeline.module';

import { SharedModule } from '../../shared';

import {
  AppCreateClusterAccessComponent,
  AppCreateContainerFieldComponent,
  AppCreateParamsInputComponent,
  AppCreatePublicIPAccessComponent,
  AppCreatePublicNetWorkAccessComponent,
  AppResourceFormComponent,
  ApplicationDeleteDialogComponent,
  ApplicationDetailComponent,
  ApplicationListCardComponent,
  ApplicationLogComponent,
  ApplicationOtherListComponent,
  ApplicationResourceReportComponent,
  ApplicationResourceReportDetailComponent,
  ApplicationStatusGaugeBarComponent,
  ApplicationUpdateComponent,
  ApplicationYamlEditDialogComponent,
  AutoScalingDialogComponent,
  AutoScalingInfoComponent,
  ContainerComponent,
  ContainerSizeUpdateDialogComponent,
  ContainerUpdateComponent,
  ContainerUpdateDifferDialogComponent,
  ContainerUpdateEnvComponent,
  ContainerUpdateEnvFromComponent,
  ContainerUpdateFormComponent,
  ContainerUpdateSizeComponent,
  ContainerUpdateVolumeComponent,
  CreateAppMultiComputeComponent,
  CreateApplicationByImageComponent,
  CreateApplicationByYamlComponent,
  EnvDialogComponent,
  EnvFormComponent,
  EnvFromDialogComponent,
  EnvFromFormComponent,
  EnvVarsComponent,
  ExternalIPDialogComponent,
  ExternalNetworkDialogComponent,
  FoldableBarComponent,
  FoldableBlockComponent,
  InternalNetworkDialogComponent,
  K8sResourceBasicInfoComponent,
  K8sResourceComponent,
  K8sResourceDetailComponent,
  K8sResourceIconComponent,
  K8sResourceUpdateComponent,
  KeyPathFromComponent,
  KeyValueInputsComponent,
  PodEnvListComponent,
  PodsScalerComponent,
  ReportsDialogComponent,
  ResourceLabelsFieldComponent,
  ResourceNetworkComponent,
  ResourceYamlPreviewDialogComponent,
  RollbackDialogComponent,
  TagsLabelComponent,
  TemplateResourceReportComponent,
  UpdateImageDialogComponent,
  UpdateLabelsDialogComponent,
  VisitAddressesComponent,
  VolumeInfoComponent,
  VolumeMountDialogComponent,
  WorkloadSelectDialogComponent,
} from './components';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    RouterModule,
    SharedModule,
    PipelineModule,
    DialogModule,
    TableOfContentsModule,
    FeatureSharedCommonModule,
  ],
  declarations: [
    ApplicationDetailComponent,
    K8sResourceComponent,
    K8sResourceDetailComponent,
    K8sResourceIconComponent,
    K8sResourceBasicInfoComponent,
    ContainerComponent,
    PodsScalerComponent,
    ApplicationYamlEditDialogComponent,
    ApplicationOtherListComponent,
    ContainerUpdateComponent,
    ContainerUpdateFormComponent,
    ContainerUpdateEnvComponent,
    ContainerUpdateEnvFromComponent,
    ResourceYamlPreviewDialogComponent,
    ContainerUpdateDifferDialogComponent,
    ApplicationDeleteDialogComponent,
    ApplicationResourceReportComponent,
    ApplicationListCardComponent,
    ApplicationStatusGaugeBarComponent,
    ApplicationLogComponent,
    ResourceLabelsFieldComponent,
    TagsLabelComponent,
    UpdateLabelsDialogComponent,
    VolumeInfoComponent,
    VolumeMountDialogComponent,
    FoldableBarComponent,
    FoldableBlockComponent,
    ContainerUpdateSizeComponent,
    ContainerUpdateVolumeComponent,
    KeyPathFromComponent,
    PodEnvListComponent,
    EnvDialogComponent,
    EnvFromDialogComponent,
    EnvFormComponent,
    EnvFromFormComponent,
    CreateApplicationByImageComponent,
    CreateApplicationByYamlComponent,
    EnvVarsComponent,
    TemplateResourceReportComponent,
    ApplicationResourceReportDetailComponent,
    AppCreateParamsInputComponent,
    AppCreateClusterAccessComponent,
    AppCreatePublicNetWorkAccessComponent,
    AppCreatePublicIPAccessComponent,
    AppCreateContainerFieldComponent,
    ReportsDialogComponent,
    KeyValueInputsComponent,
    CreateAppMultiComputeComponent,
    AppResourceFormComponent,
    VisitAddressesComponent,
    ResourceNetworkComponent,
    ExternalNetworkDialogComponent,
    ExternalIPDialogComponent,
    InternalNetworkDialogComponent,
    K8sResourceUpdateComponent,
    UpdateImageDialogComponent,
    ContainerSizeUpdateDialogComponent,
    RollbackDialogComponent,
    AutoScalingDialogComponent,
    AutoScalingInfoComponent,
    ApplicationUpdateComponent,
    WorkloadSelectDialogComponent,
  ],
  exports: [
    ApplicationDetailComponent,
    ContainerUpdateComponent,
    ApplicationListCardComponent,
    K8sResourceDetailComponent,
    K8sResourceUpdateComponent,
    CreateApplicationByImageComponent,
    CreateApplicationByYamlComponent,
    ApplicationUpdateComponent,
    WorkloadSelectDialogComponent,
  ],
  providers: [ApplicationApiService, ContainerLogApiService],
  entryComponents: [
    ApplicationYamlEditDialogComponent,
    ResourceYamlPreviewDialogComponent,
    ContainerUpdateDifferDialogComponent,
    ApplicationDeleteDialogComponent,
    UpdateLabelsDialogComponent,
    VolumeMountDialogComponent,
    EnvDialogComponent,
    EnvFromDialogComponent,
    ReportsDialogComponent,
    ExternalNetworkDialogComponent,
    ExternalIPDialogComponent,
    InternalNetworkDialogComponent,
    UpdateImageDialogComponent,
    ContainerSizeUpdateDialogComponent,
    RollbackDialogComponent,
    AutoScalingDialogComponent,
    WorkloadSelectDialogComponent,
  ],
})
export class ApplicationModule {}
